name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_call:

env:
  NPM_TOKEN: test

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ./node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci

  lint:
    needs: [bootstrap]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ./node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run lint

  test-unit:
    needs: [bootstrap]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ./node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run test:coverage

  build:
    needs: ['lint', 'test-unit']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ./node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run build --if-present
